//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClientesNuevos.F5.Autoevaluacion._1._0._0
{
    public partial class RequerimientoDeSociosComerciales
    {
    }
}
