//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientesNuevos.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AgentesAduanales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgentesAduanales() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientesNuevos.App_GlobalResources.AgentesAduanales", typeof(AgentesAduanales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string lblAcciones {
            get {
                return ResourceManager.GetString("lblAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agente aduanal mexicano.
        /// </summary>
        public static string lblAgenteMexicano {
            get {
                return ResourceManager.GetString("lblAgenteMexicano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agente aduanal americano.
        /// </summary>
        public static string lblAgenteUSA {
            get {
                return ResourceManager.GetString("lblAgenteUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Celular.
        /// </summary>
        public static string lblCelular {
            get {
                return ResourceManager.GetString("lblCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string lblCiudad {
            get {
                return ResourceManager.GetString("lblCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string lblContacto {
            get {
                return ResourceManager.GetString("lblContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string lblCorreo {
            get {
                return ResourceManager.GetString("lblCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código postal.
        /// </summary>
        public static string lblCP {
            get {
                return ResourceManager.GetString("lblCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion de la compañia.
        /// </summary>
        public static string lblDesc1 {
            get {
                return ResourceManager.GetString("lblDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agentes aduanales.
        /// </summary>
        public static string lblDesc2 {
            get {
                return ResourceManager.GetString("lblDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion de compañia filial.
        /// </summary>
        public static string lblDesc3 {
            get {
                return ResourceManager.GetString("lblDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de servicio requerido.
        /// </summary>
        public static string lblDesc4 {
            get {
                return ResourceManager.GetString("lblDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acreditación en programa de seguridad.
        /// </summary>
        public static string lblDesc5 {
            get {
                return ResourceManager.GetString("lblDesc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string lblDireccion {
            get {
                return ResourceManager.GetString("lblDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *This field is required.
        /// </summary>
        public static string lblErrorNombreC {
            get {
                return ResourceManager.GetString("lblErrorNombreC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *This field is required.
        /// </summary>
        public static string lblErrorPuesto {
            get {
                return ResourceManager.GetString("lblErrorPuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string lblEstado {
            get {
                return ResourceManager.GetString("lblEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturación.
        /// </summary>
        public static string lblFra {
            get {
                return ResourceManager.GetString("lblFra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        public static string lblInfo {
            get {
                return ResourceManager.GetString("lblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string lblNombreC {
            get {
                return ResourceManager.GetString("lblNombreC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre comercial.
        /// </summary>
        public static string lblNombreComercial {
            get {
                return ResourceManager.GetString("lblNombreComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la compañia.
        /// </summary>
        public static string lblNombreCompania {
            get {
                return ResourceManager.GetString("lblNombreCompania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de patente.
        /// </summary>
        public static string lblNoPatente {
            get {
                return ResourceManager.GetString("lblNoPatente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 1.
        /// </summary>
        public static string lblPaso1 {
            get {
                return ResourceManager.GetString("lblPaso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 2.
        /// </summary>
        public static string lblPaso2 {
            get {
                return ResourceManager.GetString("lblPaso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 3.
        /// </summary>
        public static string lblPaso3 {
            get {
                return ResourceManager.GetString("lblPaso3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 4.
        /// </summary>
        public static string lblPaso4 {
            get {
                return ResourceManager.GetString("lblPaso4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 5.
        /// </summary>
        public static string lblPaso5 {
            get {
                return ResourceManager.GetString("lblPaso5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto.
        /// </summary>
        public static string lblPuestoC {
            get {
                return ResourceManager.GetString("lblPuestoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string lblTelefono {
            get {
                return ResourceManager.GetString("lblTelefono", resourceCulture);
            }
        }
    }
}
