//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class autoevaluacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal autoevaluacion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.autoevaluacion", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requerimientos de los socios comerciales.
        /// </summary>
        internal static string lbl100 {
            get {
                return ResourceManager.GetString("lbl100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedimientos de seguridad.
        /// </summary>
        internal static string lbl110 {
            get {
                return ResourceManager.GetString("lbl110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto de origen.
        /// </summary>
        internal static string lbl120 {
            get {
                return ResourceManager.GetString("lbl120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participación / Certificación en programas de seguridad de la cadena de abastecimiento de administraciones aduanales extranjeras.
        /// </summary>
        internal static string lbl130 {
            get {
                return ResourceManager.GetString("lbl130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedimientos de Seguridad.
        /// </summary>
        internal static string lbl140 {
            get {
                return ResourceManager.GetString("lbl140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad de Contenedores y Remolques.
        /// </summary>
        internal static string lbl200 {
            get {
                return ResourceManager.GetString("lbl200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inspección de los contenedores.
        /// </summary>
        internal static string lbl210 {
            get {
                return ResourceManager.GetString("lbl210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inspección del Remolque.
        /// </summary>
        internal static string lbl220 {
            get {
                return ResourceManager.GetString("lbl220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sellos de los remolques y contenedores.
        /// </summary>
        internal static string lbl230 {
            get {
                return ResourceManager.GetString("lbl230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Almacenamiento de contenedores y remolques.
        /// </summary>
        internal static string lbl240 {
            get {
                return ResourceManager.GetString("lbl240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controles de acceso físico.
        /// </summary>
        internal static string lbl300 {
            get {
                return ResourceManager.GetString("lbl300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control de empleados.
        /// </summary>
        internal static string lbl310 {
            get {
                return ResourceManager.GetString("lbl310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control de visitantes.
        /// </summary>
        internal static string lbl320 {
            get {
                return ResourceManager.GetString("lbl320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control de Entregas (incluyendo la correspondencia).
        /// </summary>
        internal static string lbl330 {
            get {
                return ResourceManager.GetString("lbl330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abordaje y remoción de personas no autorizadas.
        /// </summary>
        internal static string lbl340 {
            get {
                return ResourceManager.GetString("lbl340", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad del personal.
        /// </summary>
        internal static string lbl400 {
            get {
                return ResourceManager.GetString("lbl400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificación previa a la contratación.
        /// </summary>
        internal static string lbl410 {
            get {
                return ResourceManager.GetString("lbl410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificación / investigación.
        /// </summary>
        internal static string lbl420 {
            get {
                return ResourceManager.GetString("lbl420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedimientos deteerminación de relaciones laborales.
        /// </summary>
        internal static string lbl430 {
            get {
                return ResourceManager.GetString("lbl430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad de los Procesos.
        /// </summary>
        internal static string lbl500 {
            get {
                return ResourceManager.GetString("lbl500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesamiento de la documentación.
        /// </summary>
        internal static string lbl510 {
            get {
                return ResourceManager.GetString("lbl510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedimientos de declaración.
        /// </summary>
        internal static string lbl520 {
            get {
                return ResourceManager.GetString("lbl520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Embarque y recepción.
        /// </summary>
        internal static string lbl530 {
            get {
                return ResourceManager.GetString("lbl530", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discrepancias de la carga.
        /// </summary>
        internal static string lbl540 {
            get {
                return ResourceManager.GetString("lbl540", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad Física.
        /// </summary>
        internal static string lbl600 {
            get {
                return ResourceManager.GetString("lbl600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cercado.
        /// </summary>
        internal static string lbl610 {
            get {
                return ResourceManager.GetString("lbl610", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puertas y casetas de vigilancia.
        /// </summary>
        internal static string lbl620 {
            get {
                return ResourceManager.GetString("lbl620", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estacionamiento.
        /// </summary>
        internal static string lbl630 {
            get {
                return ResourceManager.GetString("lbl630", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estructura del edificio.
        /// </summary>
        internal static string lbl640 {
            get {
                return ResourceManager.GetString("lbl640", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivos de cierre y control de llaves.
        /// </summary>
        internal static string lbl650 {
            get {
                return ResourceManager.GetString("lbl650", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iluminación.
        /// </summary>
        internal static string lbl660 {
            get {
                return ResourceManager.GetString("lbl660", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistemas de alrma y cámaras de vigilancia por video.
        /// </summary>
        internal static string lbl670 {
            get {
                return ResourceManager.GetString("lbl670", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad de Tecnologías de la Información.
        /// </summary>
        internal static string lbl700 {
            get {
                return ResourceManager.GetString("lbl700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Protección de contraseñas.
        /// </summary>
        internal static string lbl710 {
            get {
                return ResourceManager.GetString("lbl710", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsabilidad.
        /// </summary>
        internal static string lbl720 {
            get {
                return ResourceManager.GetString("lbl720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrenamiento de seguridad y concintización de amenazas.
        /// </summary>
        internal static string lbl800 {
            get {
                return ResourceManager.GetString("lbl800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Responda las preguntas. Es obligatorio seleccionar una opción, pero el campo de observaciones es opcional*.
        /// </summary>
        internal static string lblInstrucciones {
            get {
                return ResourceManager.GetString("lblInstrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel 1. Riesgo bajo: 75% a 100% de cumplimiento.
        /// </summary>
        internal static string lblNivel1 {
            get {
                return ResourceManager.GetString("lblNivel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel 2. Riesgo medio: 50% a 74% de cumplimiento.
        /// </summary>
        internal static string lblNivel2 {
            get {
                return ResourceManager.GetString("lblNivel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel 3. Riesgo alto: 0 a 49% de cumplimiento.
        /// </summary>
        internal static string lblNivel3 {
            get {
                return ResourceManager.GetString("lblNivel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Niveles de riesgo.
        /// </summary>
        internal static string lblNivelesRiesgo {
            get {
                return ResourceManager.GetString("lblNivelesRiesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel de Riesgo (N.R.).
        /// </summary>
        internal static string lblNR {
            get {
                return ResourceManager.GetString("lblNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero.
        /// </summary>
        internal static string lblNumero {
            get {
                return ResourceManager.GetString("lblNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        internal static string lblObservaciones {
            get {
                return ResourceManager.GetString("lblObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        internal static string lblOpciones {
            get {
                return ResourceManager.GetString("lblOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pregunta.
        /// </summary>
        internal static string lblPregunta {
            get {
                return ResourceManager.GetString("lblPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promedio de cumplimiento.
        /// </summary>
        internal static string lblPromedio {
            get {
                return ResourceManager.GetString("lblPromedio", resourceCulture);
            }
        }
    }
}
