//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Carpetilla {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Carpetilla() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Carpetilla", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acta constitutiva.
        /// </summary>
        internal static string lblAC {
            get {
                return ResourceManager.GetString("lblAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        internal static string lblAcciones {
            get {
                return ResourceManager.GetString("lblAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a actualizar.
        /// </summary>
        internal static string lblAct {
            get {
                return ResourceManager.GetString("lblAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a actualizado.
        /// </summary>
        internal static string lblActualizado {
            get {
                return ResourceManager.GetString("lblActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llenar formulario.
        /// </summary>
        internal static string lblbtnLlenar {
            get {
                return ResourceManager.GetString("lblbtnLlenar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carta de no antecedentes penales.
        /// </summary>
        internal static string lblCNAP {
            get {
                return ResourceManager.GetString("lblCNAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compañia.
        /// </summary>
        internal static string lblComp {
            get {
                return ResourceManager.GetString("lblComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compañía.
        /// </summary>
        internal static string lblCompania {
            get {
                return ResourceManager.GetString("lblCompania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a completado.
        /// </summary>
        internal static string lblCompletado {
            get {
                return ResourceManager.GetString("lblCompletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobante de domicilio.
        /// </summary>
        internal static string lblComprobanteDom {
            get {
                return ResourceManager.GetString("lblComprobanteDom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leer criterios.
        /// </summary>
        internal static string lblCriterios {
            get {
                return ResourceManager.GetString("lblCriterios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificación C-TPAT.
        /// </summary>
        internal static string lblCTPAT {
            get {
                return ResourceManager.GetString("lblCTPAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        internal static string lblDocumento {
            get {
                return ResourceManager.GetString("lblDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suelte el archivo o haga click aqui.
        /// </summary>
        internal static string lblDropMensaje {
            get {
                return ResourceManager.GetString("lblDropMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        internal static string lblEstatus {
            get {
                return ResourceManager.GetString("lblEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carta compromiso (F-12).
        /// </summary>
        internal static string lblF12 {
            get {
                return ResourceManager.GetString("lblF12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admisión de cliente nuevo (F-14).
        /// </summary>
        internal static string lblF14 {
            get {
                return ResourceManager.GetString("lblF14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criterios minimos de seguridad C-TPAT (F-20).
        /// </summary>
        internal static string lblF20 {
            get {
                return ResourceManager.GetString("lblF20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapeo de carga de flujo (F-43).
        /// </summary>
        internal static string lblF43 {
            get {
                return ResourceManager.GetString("lblF43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluación de seguridad (F-5).
        /// </summary>
        internal static string lblF5 {
            get {
                return ResourceManager.GetString("lblF5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de entrega.
        /// </summary>
        internal static string lblFecha {
            get {
                return ResourceManager.GetString("lblFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario.
        /// </summary>
        internal static string lblForm {
            get {
                return ResourceManager.GetString("lblForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el archivo correspondiente a su.
        /// </summary>
        internal static string lblInstruccion {
            get {
                return ResourceManager.GetString("lblInstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación de representante legal.
        /// </summary>
        internal static string lblIRL {
            get {
                return ResourceManager.GetString("lblIRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificación OEA.
        /// </summary>
        internal static string lblOEA {
            get {
                return ResourceManager.GetString("lblOEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opinion positiva.
        /// </summary>
        internal static string lblOpinionPositiva {
            get {
                return ResourceManager.GetString("lblOpinionPositiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pendiente.
        /// </summary>
        internal static string lblPendiente {
            get {
                return ResourceManager.GetString("lblPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poder de representante legal.
        /// </summary>
        internal static string lblPRL {
            get {
                return ResourceManager.GetString("lblPRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver resultados.
        /// </summary>
        internal static string lblResultados {
            get {
                return ResourceManager.GetString("lblResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en revision.
        /// </summary>
        internal static string lblRevision {
            get {
                return ResourceManager.GetString("lblRevision", resourceCulture);
            }
        }
    }
}
