//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Certificacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Certificacion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Certificacion", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificado.
        /// </summary>
        internal static string lblCertificado {
            get {
                return ResourceManager.GetString("lblCertificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificado no validado.
        /// </summary>
        internal static string lblCertificadoNoVal {
            get {
                return ResourceManager.GetString("lblCertificadoNoVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificado validado.
        /// </summary>
        internal static string lblCertificadoValidado {
            get {
                return ResourceManager.GetString("lblCertificadoValidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de certificacion.
        /// </summary>
        internal static string lblCodigo {
            get {
                return ResourceManager.GetString("lblCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del programa de seguridad.
        /// </summary>
        internal static string lblDescripcion {
            get {
                return ResourceManager.GetString("lblDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string lblEditar {
            get {
                return ResourceManager.GetString("lblEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string lblEliminar {
            get {
                return ResourceManager.GetString("lblEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Este campo es requerido.
        /// </summary>
        internal static string lblErrorDesc {
            get {
                return ResourceManager.GetString("lblErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Seleccione una opción.
        /// </summary>
        internal static string lblErrorOpcion {
            get {
                return ResourceManager.GetString("lblErrorOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de validación.
        /// </summary>
        internal static string lblFecha {
            get {
                return ResourceManager.GetString("lblFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ninguno.
        /// </summary>
        internal static string lblNinguno {
            get {
                return ResourceManager.GetString("lblNinguno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registros.
        /// </summary>
        internal static string lblNodata {
            get {
                return ResourceManager.GetString("lblNodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cuenta con certificación en otros programas de seguridad equivalente a C-TPAT/WCO?.
        /// </summary>
        internal static string lblPregunta {
            get {
                return ResourceManager.GetString("lblPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programa de seguridad.
        /// </summary>
        internal static string lblPrograma {
            get {
                return ResourceManager.GetString("lblPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        internal static string lblSI {
            get {
                return ResourceManager.GetString("lblSI", resourceCulture);
            }
        }
    }
}
