//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Evaluacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Evaluacion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Evaluacion", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestra compañía.
        /// </summary>
        internal static string lbl100 {
            get {
                return ResourceManager.GetString("lbl100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ya esta certificada .
        /// </summary>
        internal static string lbl1001 {
            get {
                return ResourceManager.GetString("lbl1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en C-TPAT y nuestro SVI es:.
        /// </summary>
        internal static string lbl1002 {
            get {
                return ResourceManager.GetString("lbl1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestra compañía .
        /// </summary>
        internal static string lbl120 {
            get {
                return ResourceManager.GetString("lbl120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ES.
        /// </summary>
        internal static string lbl1201 {
            get {
                return ResourceManager.GetString("lbl1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a elegible para ser miembro de C-TPAT.
        /// </summary>
        internal static string lbl1202 {
            get {
                return ResourceManager.GetString("lbl1202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es miembro o está en proceso de ser miembro C-TPAT.
        /// </summary>
        internal static string lbl130 {
            get {
                return ResourceManager.GetString("lbl130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si la respuesta a la pregunta 1.3.0 es.
        /// </summary>
        internal static string lbl131 {
            get {
                return ResourceManager.GetString("lbl131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus de cuenta.
        /// </summary>
        internal static string lbl1312 {
            get {
                return ResourceManager.GetString("lbl1312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus de revisión de su perfil de seguridad:.
        /// </summary>
        internal static string lbl1313 {
            get {
                return ResourceManager.GetString("lbl1313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No esta interesada en aplicar por el momento.
        /// </summary>
        internal static string lbl1321 {
            get {
                return ResourceManager.GetString("lbl1321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta interesada y desea recibir más información.
        /// </summary>
        internal static string lbl1322 {
            get {
                return ResourceManager.GetString("lbl1322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestra compañía comprende las normas mínimas de Seguridad C-TPAT y certifica que sus operaciones están acordes con dichas normas..
        /// </summary>
        internal static string lbl140 {
            get {
                return ResourceManager.GetString("lbl140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestra compañía.
        /// </summary>
        internal static string lbl150 {
            get {
                return ResourceManager.GetString("lbl150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO ES ELEGIBLE PARA SER MIEBRO C-TPAT.
        /// </summary>
        internal static string lbl1501 {
            get {
                return ResourceManager.GetString("lbl1501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pero está de acuerdo en cumplir con los lineamientos de seguridad.
        /// </summary>
        internal static string lbl1502 {
            get {
                return ResourceManager.GetString("lbl1502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta usted respondiendo por todas las entidades de negocio de su compañía?.
        /// </summary>
        internal static string lbl160 {
            get {
                return ResourceManager.GetString("lbl160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizado.
        /// </summary>
        internal static string lblActualizado {
            get {
                return ResourceManager.GetString("lblActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En revisión.
        /// </summary>
        internal static string lblEnRevision {
            get {
                return ResourceManager.GetString("lblEnRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Elija una opción.
        /// </summary>
        internal static string lblError {
            get {
                return ResourceManager.GetString("lblError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, responda las siguientes preguntas..
        /// </summary>
        internal static string lblInstrucciones {
            get {
                return ResourceManager.GetString("lblInstrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuestionario C-TPAT para SOCIO COMERCIAL.
        /// </summary>
        internal static string lblTitulo {
            get {
                return ResourceManager.GetString("lblTitulo", resourceCulture);
            }
        }
    }
}
