//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InformacionCompania {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformacionCompania() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.InformacionCompania", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Años de negocio.
        /// </summary>
        internal static string lblAnioNegocio {
            get {
                return ResourceManager.GetString("lblAnioNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del banco.
        /// </summary>
        internal static string lblBanco {
            get {
                return ResourceManager.GetString("lblBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar contacto.
        /// </summary>
        internal static string lblBotonRegistrar {
            get {
                return ResourceManager.GetString("lblBotonRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string lblbtnAddCF {
            get {
                return ResourceManager.GetString("lblbtnAddCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        internal static string lblBtnAtras {
            get {
                return ResourceManager.GetString("lblBtnAtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string lblBtnContinuar {
            get {
                return ResourceManager.GetString("lblBtnContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        internal static string lblBtnFinish {
            get {
                return ResourceManager.GetString("lblBtnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uso de CFDI.
        /// </summary>
        internal static string lblCFDI {
            get {
                return ResourceManager.GetString("lblCFDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar factura.
        /// </summary>
        internal static string lblCheckbox {
            get {
                return ResourceManager.GetString("lblCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLABE bancaria.
        /// </summary>
        internal static string lblClabe {
            get {
                return ResourceManager.GetString("lblClabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código postal.
        /// </summary>
        internal static string lblCP {
            get {
                return ResourceManager.GetString("lblCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos bancarios.
        /// </summary>
        internal static string lblDatosBancarios {
            get {
                return ResourceManager.GetString("lblDatosBancarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de contacto.
        /// </summary>
        internal static string lblDatosContacto {
            get {
                return ResourceManager.GetString("lblDatosContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de facturación.
        /// </summary>
        internal static string lblDatosFra {
            get {
                return ResourceManager.GetString("lblDatosFra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección fiscal.
        /// </summary>
        internal static string lblDireccionFiscal {
            get {
                return ResourceManager.GetString("lblDireccionFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección de facturación es diferente a la dirección fiscal.
        /// </summary>
        internal static string lblDireccionIgual {
            get {
                return ResourceManager.GetString("lblDireccionIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección de facturación.
        /// </summary>
        internal static string lblDirFra {
            get {
                return ResourceManager.GetString("lblDirFra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar contacto.
        /// </summary>
        internal static string lblEditContacto {
            get {
                return ResourceManager.GetString("lblEditContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Especifique los años de servicio que tiene el negocio.
        /// </summary>
        internal static string lblErrorAnios {
            get {
                return ResourceManager.GetString("lblErrorAnios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Especifique el nombre del banco.
        /// </summary>
        internal static string lblErrorBanco {
            get {
                return ResourceManager.GetString("lblErrorBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Ingrese la CLABE bancaria.
        /// </summary>
        internal static string lblErrorClabe {
            get {
                return ResourceManager.GetString("lblErrorClabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Especifique el código postal o zip code.
        /// </summary>
        internal static string lblErrorCP {
            get {
                return ResourceManager.GetString("lblErrorCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Especifique una direccion.
        /// </summary>
        internal static string lblErrorDireccion {
            get {
                return ResourceManager.GetString("lblErrorDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Ingrese un numero de cuenta.
        /// </summary>
        internal static string lblErrorNoCuenta {
            get {
                return ResourceManager.GetString("lblErrorNoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Especifique el nombre comercial de la compañia.
        /// </summary>
        internal static string lblErrorNombreComercial {
            get {
                return ResourceManager.GetString("lblErrorNombreComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Especifique el nombre completo de la comañia.
        /// </summary>
        internal static string lblErrorNombreEmpresa {
            get {
                return ResourceManager.GetString("lblErrorNombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *RFC o W9 requerido.
        /// </summary>
        internal static string lblErrorRFC {
            get {
                return ResourceManager.GetString("lblErrorRFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Especifique el RFC del banco.
        /// </summary>
        internal static string lblErrorRFCBanco {
            get {
                return ResourceManager.GetString("lblErrorRFCBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de pago.
        /// </summary>
        internal static string lblFormaPago {
            get {
                return ResourceManager.GetString("lblFormaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llene los campos necesarios y haga clic en el boton &apos;Registrar contacto&apos;.
        /// </summary>
        internal static string lblHint {
            get {
                return ResourceManager.GetString("lblHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metodo de pago.
        /// </summary>
        internal static string lblMetodoPago {
            get {
                return ResourceManager.GetString("lblMetodoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moneda.
        /// </summary>
        internal static string lblMoneda {
            get {
                return ResourceManager.GetString("lblMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de cuenta.
        /// </summary>
        internal static string lblNoCuenta {
            get {
                return ResourceManager.GetString("lblNoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pais.
        /// </summary>
        internal static string lblPais {
            get {
                return ResourceManager.GetString("lblPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extranjero.
        /// </summary>
        internal static string lblPersonaExtranjera {
            get {
                return ResourceManager.GetString("lblPersonaExtranjera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fisica.
        /// </summary>
        internal static string lblPersonaFisica {
            get {
                return ResourceManager.GetString("lblPersonaFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moral.
        /// </summary>
        internal static string lblPersonaMoral {
            get {
                return ResourceManager.GetString("lblPersonaMoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Régimen fiscal.
        /// </summary>
        internal static string lblRegimen {
            get {
                return ResourceManager.GetString("lblRegimen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        internal static string lblRegistrar {
            get {
                return ResourceManager.GetString("lblRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RFC/W9.
        /// </summary>
        internal static string lblRFC {
            get {
                return ResourceManager.GetString("lblRFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RFC del banco.
        /// </summary>
        internal static string lblRFCBAnco {
            get {
                return ResourceManager.GetString("lblRFCBAnco", resourceCulture);
            }
        }
    }
}
