//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Servicios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Servicios() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Servicios", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Almacenaje.
        /// </summary>
        internal static string lblAlmacenaje {
            get {
                return ResourceManager.GetString("lblAlmacenaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Almacen de deposito.
        /// </summary>
        internal static string lblAlmacenDeposito {
            get {
                return ResourceManager.GetString("lblAlmacenDeposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cajas.
        /// </summary>
        internal static string lblCajas {
            get {
                return ResourceManager.GetString("lblCajas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carbón.
        /// </summary>
        internal static string lblCarbon {
            get {
                return ResourceManager.GetString("lblCarbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga seca.
        /// </summary>
        internal static string lblCargaSeca {
            get {
                return ResourceManager.GetString("lblCargaSeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        internal static string lblComentarios {
            get {
                return ResourceManager.GetString("lblComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de mercancía.
        /// </summary>
        internal static string lblDescripcion {
            get {
                return ResourceManager.GetString("lblDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportación.
        /// </summary>
        internal static string lblExportacion {
            get {
                return ResourceManager.GetString("lblExportacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ferrocarril.
        /// </summary>
        internal static string lblFerrocarril {
            get {
                return ResourceManager.GetString("lblFerrocarril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importación.
        /// </summary>
        internal static string lblImportacion {
            get {
                return ResourceManager.GetString("lblImportacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de productos.
        /// </summary>
        internal static string lblInfoProd {
            get {
                return ResourceManager.GetString("lblInfoProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logística.
        /// </summary>
        internal static string lblLogistica {
            get {
                return ResourceManager.GetString("lblLogistica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material peligroso.
        /// </summary>
        internal static string lblMaterialPeligroso {
            get {
                return ResourceManager.GetString("lblMaterialPeligroso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro.
        /// </summary>
        internal static string lblOtro {
            get {
                return ResourceManager.GetString("lblOtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cúal?.
        /// </summary>
        internal static string lblPregunta {
            get {
                return ResourceManager.GetString("lblPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Químicos.
        /// </summary>
        internal static string lblQuimicos {
            get {
                return ResourceManager.GetString("lblQuimicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renta de equipo.
        /// </summary>
        internal static string lblRentaEquipo {
            get {
                return ResourceManager.GetString("lblRentaEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio dedicado.
        /// </summary>
        internal static string lblServicioDedicado {
            get {
                return ResourceManager.GetString("lblServicioDedicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transbordo.
        /// </summary>
        internal static string lblTransbordo {
            get {
                return ResourceManager.GetString("lblTransbordo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transportación.
        /// </summary>
        internal static string lblTransportacion {
            get {
                return ResourceManager.GetString("lblTransportacion", resourceCulture);
            }
        }
    }
}
